# Generated by Django 4.1 on 2022-08-29 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='smartcontract',
            old_name='contract_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='smartcontract',
            old_name='contract_creator',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='smartcontract',
            name='contract_block',
        ),
        migrations.RemoveField(
            model_name='smartcontract',
            name='contract_blockchain',
        ),
        migrations.AddField(
            model_name='smartcontract',
            name='block_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='smartcontract',
            name='creation_datetime',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='smartcontract',
            name='blockchain',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='cryptocurrencies.blockchain'),
        ),
    ]
