# Generated by Django 4.1 on 2022-09-05 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0002_blockchain_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockchain',
            options={'verbose_name': 'Блокчейн', 'verbose_name_plural': 'Блокчейны'},
        ),
        migrations.AlterModelOptions(
            name='smartcontract',
            options={'verbose_name': 'Смарт-контракт', 'verbose_name_plural': 'Смарт-контракты'},
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='address',
            field=models.CharField(max_length=42, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='block_number',
            field=models.IntegerField(default=None, verbose_name='Номер блока'),
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='blockchain',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='cryptocurrencies.blockchain', verbose_name='Блокчейн'),
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='creation_datetime',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='creator',
            field=models.CharField(blank=True, max_length=42, verbose_name='Создатель'),
        ),
    ]
