# Generated by Django 4.1 on 2022-08-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=200)),
                ('contract_blockchain', models.CharField(max_length=10)),
                ('contract_creator', models.CharField(blank=True, max_length=200)),
                ('contract_block', models.IntegerField(max_length=200)),
            ],
        ),
    ]
